### ISSUE TITLE
FMS Interpolator unable to handle annual emissions

### ISSUE THREAD

**Issue by fabienpaulot** [NOAA-GFDL/FMS#1343]
**Is your feature request related to a problem? Please describe.**
The interpolator routine (FMS) is unable to handle annual emission files (1 timestep per year). If I turn my annual timeseries into a monthly timeseries, it works well but it increases the size of the input by an order of magnitude.

**Describe the solution you'd like**
Be able to use gridded annual emissions (time units could be fractional year for instance)

**Comment by fabienpaulot** [comment]
Hi,
Here you are 
~Fabien.Paulot/Downloads/emission.sf6.nc

**Comment by mlee03** [comment]
Thank you!

**Comment by mlee03** [comment]
@fabienpaulot, sorry to bother you again, but I just wanted to verify that if the time units are in months, _e.g_ the time units are "months since YYYY-MM-DD", the model runs and gives you expected answers?  Would you still have that emission files (with time units in months)  you could share with us?
