### ISSUE TITLE
reading remapping weights generated by fregrid/ESMF into data_override

### ISSUE THREAD

**Issue by raphaeldussin** [NOAA-GFDL/FMS#1399]
**Is your feature request related to a problem? Please describe.**

The horizontal remapping (horiz_interp) called from data_override is likely to become more and more
costly as horizontal resolution of forcing sets increases and has to be done for every job. Reading pre-computed
remapping weights could save time AND allow to use weights generated by other methods (e.g. ESMF's patch,...)

**Describe the solution you'd like**

In the data_table the interpolation field (usually bilinear/bicubic) would be able to receive a filename from
which the weights would be read and passed to data_override

**Describe alternatives you've considered**

Remapping to the model grid results in duplication of large files and need to be done for each model resolution so
is not terribly practical.

**Comment by uramirez8707** [comment]
> In the data_table the interpolation field (usually bilinear/bicubic) would be able to receive a filename from
which the weights would be read and passed to data_override

Are you referring to the weights used by horiz_interp to do the interpolation?

Do you have an example of what this weight file will look like?

**Comment by raphaeldussin** [comment]
correct!

I do have some old examples of comparing weights between fregrid and esmf here:
`/work/Raphael.Dussin/sandbox/FREEDOM-NCtools/FREEDOM-NCtools/FRE2ESMF/examples`

they both are variations over storing a sparse matrix. There might be some choices to make on what format to support (or both).

**Comment by theresa-morrison** [comment]
This feature would be helpful for some of the regional domains being developed. In particular, our Arctic configurations have a problem because the regional ocean domain is not re-entrant but the forcing from the data atmosphere should be interpolated across the zonal boundary. 

Currently to solve this problem, all the forcing data must be interpolated onto the ocean grid offline, which for high resolution or long runs is a large volume of data to produce an manage.  What Raf has suggested here would allow the correct weights for the atmosphere interpolation to be generated offline and used by FMS solving any issues at the seam in the forcing data.

I am really interested in having this feature in order to develop accurate regional Arctic simulations.

**Comment by bensonr** [comment]
The FMS development team will support and develop the logic needed to read in fregrid format "weight" files to use within data override for interpolation.

We do not recommend anyone using re-gridded time series files at native grid resolutions and hence will not be including any logic for outputting weight-files from horiz-interp to enable that functionality.  Our history with attempts at this have lead to increased memory use, IO load, and runtimes as well as avoidable pressure on the various distributed filesystems.

As for other interpolation weight files or formats, such as those from ESMF, the FMS infrastructure is open development and accepts community contributions.  Users are encouraged to implement any desired functionality and submit it for inclusion.
