### ISSUE TITLE
configure.ac test for Apple OS type fails for some Mac OS systems

### ISSUE THREAD

**Issue by underwoo** [NOAA-GFDL/FMS#140]
The check in the configure.ac is not fully Mac OS X portable.  Some Mac OS X systems set OSTYPE to have `darwin[0-9]+`, instead of just `darwin`.  Something more portable should be used.

**Comment by edwardhartnett** [comment]
This turns out to be a poor choice of implementation style. Do not write your code for apple, or any other operating system. Instead, write to the features of that operating system.

So you should never define an "APPLE" pre-processor for your code. What is it about Apple builds that you are trying to fix with this?

Writing OS specific code is a dead end. You don't want to support that in your build system. Make the programmers go one step further and learn what feature is under question, not just lazily resolve it to the level of the operating system. That is not good enough.
