### ISSUE TITLE
Potential issue with `Where` statements in debug mode

### ISSUE THREAD

**Issue by JosephMouallem** [NOAA-GFDL/FMS#1614]
Hi all,

I am encountering issues with `where` statements when running SHiELD/MOM6 in debug mode.
For example, the model performs a division by zero and crashes in xgrid.F90 when computing the inverse area, where `grid%area>0` so not sure how the division by zero is happening in this context:
https://github.com/NOAA-GFDL/FMS/blob/23df6d7a905aaa9618e597b82c49b56009a0caa2/exchange/xgrid.F90#L1973-L1976

A similar issue arises in the monin obukhov routine:
https://github.com/NOAA-GFDL/FMS/blob/23df6d7a905aaa9618e597b82c49b56009a0caa2/monin_obukhov/include/monin_obukhov_inter.inc#L248-L253

I am using the standard SHiELD template and compile flags: https://github.com/NOAA-GFDL/SHiELD_build/blob/main/site/intel.mk.

These issues are specific to DEBUG mode; everything works fine when compiling in REPRO mode.

**Comment by J-Lentz** [comment]
Closing because this isn't an issue with FMS per se.

Floating point exceptions are enabled by the main program due to `-fpe0` and `-ftrapuv` in the debug-mode mkmf flags, while optimization of FMS code causes speculative execution of divide-by-zero cases in the `where` statement without regard for the mask condition. Possible solutions are to add `-fp-speculation=safe` to the FMS build flags or to build FMS in debug mode when linking it with a debug-mode main program.
