### ISSUE TITLE
Remove the use of `bats` in testing

### ISSUE THREAD

**Issue by underwoo** [NOAA-GFDL/FMS#221]
**Is your feature request related to a problem? Please describe.**
The Bash Automated Testing System ([bats](https://github.com/sstephenson/bats/commits/master) is currently used to produce TAP style output.  Using `bats` adds an additional requirement in order for a user to test the build of FMS, especially since `bats` is not a base package installed by \*nix OSes.  We would like to have `bats` removed from the testing scripts for libFMS.

**Describe the solution you'd like**
Ideally, we would like to have a solution that would preserve the TAP output, but we understand that may be difficult as it may introduce a dependency on some other utility.  Thus, we would like some basic solution that will work with both the test harness system built into both GNU Autotools and CMake build systems.

**Comment by edwardhartnett** [comment]
I would propose to solve this with the solution I describe in #169.

Regular sh shell scripts can be used to run tests, as is done in netcdf-c, netcdf-fortran, HDF5, PIO, and other packages. Since sh is standard on all unix systems this is maximally portable. These scripts are then run from Makefile.am and CMakeLists.txt files. (See netcdf-c for good examples.)

**Comment by underwoo** [comment]
Your proposal in #169 is sufficient.

**Comment by edwardhartnett** [comment]
Actually the TAP style output is not a problem for the shell scripts, so we can keep that.

**Comment by edwardhartnett** [comment]
OK, actually TAP style output is a huge pain. So I will jettison that desirement...
