### ISSUE TITLE
Is support for mkmf still required? Can we stop using .inc and .h files instead of .F90 files?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-GFDL/FMS#243]
**Is your feature request related to a problem? Please describe.**
Use of .h and .inc files defeats all code analysis tools. Is there some reason you can't use .F90 files like all other fortran programmers?

**Describe the solution you'd like**
.inc files should only be used in the standard way, to provide constants and definitions. .h files should never be used by Fortran programs. Fortran code should be in .F90 files, so that compilers, tools, and other programmers can find the code.

**Describe alternatives you've considered**
No need for an alternative. Doing things the correct way is better.

**Additional context**
If mkmf support is still required, perhaps we can modify it to honor a configuration file that would like the F90 files it should treat as modules, allowing the use of F90 files elsewhere in the build without confusing mkmf. Or, even better, just stop using mkmf.

**Comment by underwoo** [comment]
Use of `mkmf` will be in use for several more months, and possibly more than a year.  This is due to several of the other GFDL model components not adopting a different build system at the same time.  We have also discovered some components/repositories that require significant modifications to allow other build system to work.

As of the `.h` and `.inc` file, some of these will need to remain until we rewrite significant portions of the FMS infrastructure.  many of the `.inc` and `.h` files (for Fortran) are used as poor man's templating system for Fortran.  We know of the many difficulties that this can (and does) introduce.  Many of our current internal developer do want to drop this use of the _include_ files in Fortran.

**Comment by edwardhartnett** [comment]
I believe you can decouple FMS from your other projects by building and installing a versioned release of FMS, and having all other packages find it as they now find netCDF. In that case, mkmf need never be run on FMS code, even if it is still used on other projects. You are already doing the versioned releases, so now you just need to use them, instead of having users clone your repo.

I am glad you want to move away from the include file mess. That is wise. However, until you decouple from mkmf you cannot do anything else, because of how mkmf works, correct? So even new work is being done in a way that will require rework. This is unfortunate.

What I am really wondering is whether I can add *.F90 tests to test_fms directories without breaking mkmf? Does mkmf go into the test_fms directory?

**Comment by underwoo** [comment]
The use of the include files in several of the Fortran files (mainly the files in mpp) has nothing to do with `mkmf` or how it operates.  The way the files are included is to create many similar interfaces -- that only differ in their return type and/or input parameter types.  Until a major rewrite is done (if the current mpp/fms rewrite doesn't resolve the issue ATT), these include files will exist for all build systems.

We did update `mkmf` to not enter `test*` directories unless that directory unless explicitly told to enter that directory.  Any test can be added to the `test_fms` directory, and it will not affect `mkmf`.

**Comment by edwardhartnett** [comment]
OK, thanks for all the clarifications. I will start addng tests, knowing that's safe with mkmf.

I will close this issue.
