### ISSUE TITLE
Axis for regional diagnostics are not written correctly

### ISSUE THREAD

**Issue by uramirez8707** [NOAA-GFDL/FMS#383]
**Describe the bug**
The axis for regional diagnostics are not written correctly. 
Each of the cores that are writing the regional diagnostics are writing the whole region instead of their own chunk. 

**To Reproduce**
Run @nikizadehgfdl  OMIP run with 442 cores and regional diagnostics. 

The regional variable `volcello` is written by 8 cores, each core writes their own file (`19480101.ocean_Agulhas_section.nc.XXXX`). 
If you run with current master, in each file the yaxis has a size of 132. 

But if you run with **xanadu** code: 
In each file the yaxis has a size of {16,18,18,18,18,18,18,8}
(which totals 132)

The end file (after it is combined in fre, `19480101.ocean_Agulhas_section.nc`) is exactly (bitwise) the same as `19480101.ocean_Agulhas_section.nc.0001`. 

But you compared the end file with Xanadu's, the answers are "different" for points that are outside the chunk of the first core (for all y's greater than 16). 

**Expected behavior**
Behavior should be the same as *Xanadu* code

**System Environment**
Describe the system environment, include:
This happens in any system.

**Additional context**
N/A

**Comment by uramirez8707** [comment]
@ngs333

**Comment by ngs333** [comment]
Diag_manager seems to purposefully use the global axis length instead of the sub-axis length. Not sure why but it may be part of the design. 

Running through the debugger for the experiments described by  uramirez8707 in comments above, in file diag_output.F90, function write_axis_metadata is where the start and end of the axis is determined. More specifically, 
Lines 386 -  389 are executed, these are:
 type is (FmsNetcdfFile_t) !< For regional X and Y axes, treat as any other axis
call register_axis(fptr, axis_name, dimension_length=size(axis_data))
 istart = lbound(axis_data,1)
  iend = ubound(axis_data,1)

and the data is latter  (by line 400) written :
 call write_data(fptr, axis_name, axis_data(istart:iend) )

But earlier (line 360) in that subroutine :
length = get_axis_global_length(id_axis)
       ALLOCATE(axis_data(length))

 For the experiments we are running, we should sometimes have different istart and iend for different regional axis. But in the code above, iend  is always equal to length (returned from get_axis_global_length). However, notice the comment on the code above: "For regional X and Y axes, ...". This re-enforces the intention of the code and perhaps it is part of the design?

**Comment by thomas-robinson** [comment]
In diag_output.F90 at line 386:
```fortran
call mpp_get_data_domain (domain,length,istart,iend)
call register_axis(fptr, axis_name, dimension_length=length 
```
Then you don't need to set istart and iend.  Go right into `register_field`

**Comment by thomas-robinson** [comment]
@uramirez8707 Do you have the correct output saved for comparison (Combined and uncombined)?

**Comment by uramirez8707** [comment]
@ngs333 

The uncombined files:
/lustre/f2/scratch/gfdl/Uriel.Ramirez/work/FMS2020.01_mom6_ESM4_v1.0.3/OM4p5_CORE2_IAF_COBALT_abio_csf_mle200_1x0m2d_442x1o1.o202963317/REF_HISTORY/

I think this is for a debug run. 

This is a combined one (with all the diagnostics), but I only have one for a prod run ... 
/lustre/f2/scratch/gfdl/Uriel.Ramirez/master_20200123_mom6_2019.08.08/OM4p5_CORE2_IAF_COBALT_abio_csf_mle200/ncrc3.intel16-prod/archive/1x0m2d_442x1o/history/19480101.nc.tar

**Comment by thomas-robinson** [comment]
@nikizadehgfdl and @uramirez8707 There is a crash when running in debug mode:
```
forrtl: error (73): floating divide by zero
Image              PC                Routine            Line        Source             
fms_MOM6_SIS2_com  00000000049E334A  generic_abiotic_m         909  generic_abiotic.F90
fms_MOM6_SIS2_com  00000000024D09A5  generic_tracer_mp         505  generic_tracer.F90
fms_MOM6_SIS2_com  000000000150F072  mom_generic_trace         644  MOM_generic_tracer.F90
fms_MOM6_SIS2_com  0000000001A7113E  mom_tracer_flow_c         524  MOM_tracer_flow_control.F90
fms_MOM6_SIS2_com  00000000015EA46D  mom_diabatic_driv        2110  MOM_diabatic_driver.F90
fms_MOM6_SIS2_com  00000000013C1922  mom_mp_step_mom_t        1180  MOM.F90
fms_MOM6_SIS2_com  00000000013B056A  mom_mp_step_mom_          737  MOM.F90
fms_MOM6_SIS2_com  000000000111FCD6  ocean_model_mod_m         556  ocean_model_MOM.F90
fms_MOM6_SIS2_com  000000000040F4A8  MAIN__                   1085  coupler_main.F90
fms_MOM6_SIS2_com  000000000040A1BE  Unknown               Unknown  Unknown
```

This seems unrelated to anything related to the diag manager.  Do either of you know what we can do about this (other than compile in prod)?

**Comment by thomas-robinson** [comment]
11:10pm on Sunday night.  Yay...

This XML does not run in debug mode.  That makes debugging a lot of fun. 

Here is my understanding of the problem which I don't think I have the knowledge to solve in 1 day:

1. When a `subaxis` is set up in the diag_manager, a 2D domain is set up with it also. This 2D domain does not have an IO domain. 
2. There are two options to open a file in fms2_io: with a domain or without a domain.  If you open this type of file *with* a domain, it fails because there is no IO domain. If you open it without a domain, you lose all of the domain information. When diag_manager inquires about the axis and its data, it just gets and writes the full data because it doesn't know anything about what section of the data the PE has.  

Maybe @underwoo or @menzel-gfdl has some insight into how to work with this problem?

**Comment by thomas-robinson** [comment]
ok, 12:46am.  I figured it out.  Instead of 
```fortran
call mpp_get_data_domain(domain, istart, iend, length)
call register_axis(fptr, axis_name, dimension_length=length)
```
you have to do a little math to get the indices correct:
```fortran
call mpp_get_global_domain(domain, gstart, gend, glength)  !< Get the global indicies
call mpp_get_compute_domain(domain, cstart, cend, clength) !< Get the compute indicies
iend =  cend - gstart + 1     !< Get the array indicies for the axis data
istart = cstart - gstart + 1 
call register_axis(fptr, axis_name, dimension_length=clength)
...
call write_data(fptr, axis_name, axis_data(istart:iend) )
```

This should produce the correct output.  @ngs333 is going to test it, and then put in the PR.
