### ISSUE TITLE
Enable mpp_domains tests in test_fms/mpp

### ISSUE THREAD

**Issue by bensonr** [NOAA-GFDL/FMS#484]
**Describe the bug**
Because of #482 all tests in test_mpp_domains2.sh are skipped.

**To Reproduce**
Use autotools build and run make check and look at the test_fms/mpp/test_mpp_domains2.sh.log 

**Expected behavior**
Tests that can be correctly executed should be.

**System Environment**
All

**Additional context**
N/A

**Comment by edwardhartnett** [comment]
On general issue with all the FMS testing is that it is very complex.

That is, you have a dearth of simple tests, the kind that make it easy to debug a problem. A complex test can be good at finding a range of problems, but debugging is made much more difficult by the complexity of the test code.

In netcdf-c, we have a progression of tests, from very simple to more and more complex. We have a test program called nc_test which attempts to test everything exhaustively, but we also have hundreds of tests which just test one thing at a time. The nc_test program is good for assurance that everything is working, but I long ago learned that if it finds an error, the best thing to do is to add a simple test just for that error. Debugging the problem within nc_test is too complex, because there is too much going on.

In a simple test, you want to involve as little other code as possible. For example, the test fms2_io/test_simple_io.F90 attempts to use as few modules as possible to do I/O. There are no command line arguments or test options (these are a mistake in all cases), there is not extensive setup and teardown. As a result, it's very easy to see what is happening. A test failure here would involve the least amount of other code.

I suggest that, as you assign programmers to add tests, you tell them to make many simple tests, instead of one complex test that attempts to do everything.

**Comment by bensonr** [comment]
There is a project <https://github.com/NOAA-GFDL/FMS/projects/6> in the FMS
github tracking the exact thing you propose.  We are starting with the
basic functionality of everything within mpp_init and will be expanding as
we go forward.  As you create simple tests to help out, please assign them
to this project.

**Comment by edwardhartnett** [comment]
Wow, terrific! I like the methodical approach. I will assign my testing tasks to this project as appropriate.

This approach will yield some great testing. Are you measuring code coverage? It's invaluable in writing unit tests like this. You can easily see what is being tested. I'll attach a snapshot from the netCDF code coverage report, so you can see what I mean. (The line of code in red is one that is not being tested.)

I tried to set this up a few weeks ago for FMS but the use of the inc files defeated my efforts. However, I'm sure it can be done with more effort...

![image](https://user-images.githubusercontent.com/38856240/85568399-e3634880-b5ee-11ea-828b-163e825e7c7a.png)

**Comment by colingladueNOAA** [comment]
I assigned your mpp_domains test to this project yesterday and look forward to seeing more.
