### ISSUE TITLE
'unsupported type' errors in fms2_io unit tests with AOCC compiler 

### ISSUE THREAD

**Issue by mlee03** [NOAA-GFDL/FMS#616]
**Describe the bug**
Similar to Issue #581, ``test_fms2_io`` and ``test_atmosphere_io`` unit tests fail with AOCC compilers with the error, "FATAL from PE     1: unsupported type."

**To Reproduce**
On the AMD machine, 

1. source /home/Mikyung.Lee/bin/setup_fms aocc
2. autoreconf -iv
3. ./configure --disable-shared
4. make check

**Expected behavior**
All make check should pass with AOCC compiler 

**System Environment**
- OS: AMD machine
- Compiler(s): AOCC/2.2.0
- MPI type, and version: openmpi/4.0.4
- netCDF Version: netcdf/4.6.1
- Configure options: Any additional flags, or macros passed to configure

**Additional context**
As done in GH-582, ``trim()`` to ``register_variable_attribute`` calls should be added in ``fms2_io``

**Comment by uramirez8707** [comment]
In addition to that the `test_atmosphere_io` test fails with the error:

``` FATAL from PE     0: character buffer is too small; increase length. ```

The crash happens in this `read_data` call:
https://github.com/NOAA-GFDL/FMS/blob/e7e48839ab25cc9405abe5d8418e1b6ee6fb2d69/test_fms/fms2_io/test_atmosphere_io.F90#L410

I think because of the `(1)` a string of length 1 is sent and not the first element as it was intended. 
https://github.com/NOAA-GFDL/FMS/blob/e7e48839ab25cc9405abe5d8418e1b6ee6fb2d69/test_fms/fms2_io/test_atmosphere_io.F90#L75
