### ISSUE TITLE
History file time_bnds variable attributes missing_value, _FillValue, units are not CF-compliant and cause fregrid to fail sometimes

### ISSUE THREAD

**Issue by ceblanton** [NOAA-GFDL/FMS#668]
**Describe the bug**
Sometimes, history file `time` and `time_bnds` are different types (float versus double). When this occurs, fregrid will fail, complaining about `missing_value` or `_FillValue` types.

The solution is to omit these 3 variable attributes currently in `time_bnds`: `missing_value`, `_FillValue`, and `units`. These are not CF compliant (see section 7.1, https://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#cell-boundaries). If the 3 attributes are omitted, fregrid will process any combination of type in `time` and `time_bnds`

**To Reproduce**
Certain combinations of diagnostics and FMS versions bring out this behavior. See https://github.com/NOAA-GFDL/FRE-NCtools/issues/33

**Expected behavior**
History files should be as CF-compliant as possible to facilitate downstream data tools such as fregrid.

**System Environment**

**Additional context**
Example files and more discussion on the FRE-NCtools issue (https://github.com/NOAA-GFDL/FRE-NCtools/issues/33)

**Comment by uramirez8707** [comment]
Regarding the different types between `time` and `time_bnds`:

1. This only happens when using fms2io in diag_manager. If the `use_mpp_io flag` nml flag is set to true the types of `time` and `time_bnds` will be the same. 
2. When using fms2io,  `time` and `time_bnds` end up being different types, when compiling FMS to use floats `-real-size 32`. 

The axis data (`time`) is hard coded to be `double` here:
https://github.com/NOAA-GFDL/FMS/blob/a671396616ae663c05db750f0c7f59d2e07ffa57/diag_manager/diag_output.F90#L382

The *_bnds is defined as whatever type you compile with. In the case where you compile with `real-size 32` it will be floats. 
https://github.com/NOAA-GFDL/FMS/blob/a671396616ae663c05db750f0c7f59d2e07ffa57/diag_manager/diag_util.F90#L2075-L2079

pack_size determines the type and it is defined:
https://github.com/NOAA-GFDL/FMS/blob/a671396616ae663c05db750f0c7f59d2e07ffa57/diag_manager/diag_data.F90#L459

BUT it gets overwritten here #classic
https://github.com/NOAA-GFDL/FMS/blob/a671396616ae663c05db750f0c7f59d2e07ffa57/diag_manager/diag_manager.F90#L3840

so it gets registered as a `float`:
https://github.com/NOAA-GFDL/FMS/blob/a671396616ae663c05db750f0c7f59d2e07ffa57/diag_manager/diag_output.F90#L960

I think this needs to be updated to be consistent ...
