### ISSUE TITLE
Travis-CI trusty openMPI missing mpi_comm_create_group

### ISSUE THREAD

**Issue by underwoo** [NOAA-GFDL/FMS#90]
The openMPI library used in the trusty travis-ci image does not have `mpi_comm_create_group`, which was added to libFMS in the latest release.  The `.travis.yml` file needs to be updated to either use mpich2, or to a newer (xenial) image.

**Comment by marshallward** [comment]
BTW my apologies to the team for slipping this in, I had intended to discuss it more but we ended up working on unrelated issues and I forgot to raise it again.

**Comment by marshallward** [comment]
For the sake of the ticket, I'll document the issue here.  `MPI_Comm_create_group` was used for its ability to create subcommunicators that only span a subset of ranks.  Otherwise one must completely divide the ranks into separate subcommunicators.  It was not an essential change, but it felt like the "correct" decision.

The issue is that this is am MPI 3 function, and OpenMPI 1.6.x does not support it, which is the current default in Travis.  Either switching to MPICH or a xenial, which uses OpenMPI 1.10.x will support the function.
