### ISSUE TITLE
FMS profiling crash

### ISSUE THREAD

**Issue by sanAkel** [NOAA-GFDL/FMS#908]
**Describe the bug**

Addition of: 
`&fms_nml print_memory_usage=.true. domains_stack_size = 24000000 clock_grain = 'MODULE' clock_flags='DETAILED' /`

>causes a 21,600 core run to crash with what appears to be a stack corruption error (probably at a collective call MPI_Gather not 100% sure yet though)

**Please see**:

https://github.com/GEOS-ESM/GEOSgcm_App/pull/289#issuecomment-1033996252

@marshallward, @aoloso would be able provide the exact **configuration** details. Thanks!

**Comment by thomas-robinson** [comment]
@sanAkel and @aoloso if this is a system issue, then do you still need someone to look into it?

**Comment by sanAkel** [comment]
> @sanAkel and @aoloso if this is a system issue, then do you still need someone to look into it?

@thomas-robinson that would be good, but I don't know much (or anything!) about @aoloso's test!

**Comment by thomas-robinson** [comment]
@sanAkel @aoloso There seem to be some mixed signals here, so I'm unsure what we can do for you.  Is this a system issue?  What type of system is this running on?  Do you have a small-*code* example that we can run that would reproduce this issue.   Can you confer with each other and let us know exactly what the problem is, and what we can do on our end to help?

**Comment by sanAkel** [comment]
Thank you @thomas-robinson, will do!

**Comment by sanAkel** [comment]
[All seems okay at our end](https://github.com/GEOS-ESM/GEOSgcm_App/pull/289#issuecomment-1043062405). Appreciate your attention. Thanks!
